CREATE TABLE
    chats (
        chat_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        chat_name TEXT NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
    );